name: Welcome
on:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRST_ISSUE: |
            👋 @{{ author }}
             Thanks for opening your first issue here!
          FIRST_PR: |
            👋 @{{ author }}
            Thanks for opening this pull request!

          FIRST_PR_MERGED: |
            🎉 @{{ author }}
            Congrats on merging your first pull request!
